spring.application.name=suwapatha
spring.data.mongodb.uri=mongodb+srv://hibaraheem10_db_user:jHDwTFY8Hq5OhO76@cluster0.zah32oj.mongodb.net/Suwapatha?retryWrites=true&w=majority

cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000

jwt.secret=c3V3YXBhdGhhLXNlY3VyZS1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24tbXVzdC1iZS1hdC1sZWFzdC0zMi1jaGFycw==
jwt.expiration=86400000

ffwd kikx mpfe atol
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hibaarahee1234@gmail.com
spring.mail.password=ffwd kikx mpfe atol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
false
